sudo: false

language: cpp

matrix:
    include:
      - os: osx
        compiler: clang
#FIX THIS
#      - os: linux
#        dist: trusty
#        compiler: gcc
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - lcov
    fast_finish:
     - true


before_install:
  # Set alias for readability
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then LINUX=true; fi
  - if [[ $LINUX ]]; then gem install coveralls-lcov; fi

install:
  - mkdir $HOME/carlsim5_install
  - export CARLSIM5_INSTALL_DIR=$HOME/carlsim5_install
  - export CARLSIM5_NO_CUDA=1
  - if [[ $LINUX ]]; then export CARLSIM5_COVERAGE=1; fi
  - cd external/googletest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../..
  - pwd
  - make distclean
  - make release_nocuda -j4
  - make install

script:
  - make test_nocuda
  - travis_wait 49 ./carlsim/test/carlsim_tests --gtest_filter=-*_MultiGPU:*_Adv

after_success:
- if [[ $LINUX ]]; then lcov -b . -d . -c -o ./coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "/usr*" -o coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "external/*" -o coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "*.h" -o coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "*.cu" -o coverage.info; fi
- if [[ $LINUX ]]; then coveralls-lcov coverage.info; fi
